// react/src/pages/redux/components/activity-reported-duration-of-norm.tsx
import {
	type FC,
} from "react";

import {
	type ActivityId,
} from "@/features/activity/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectReportedDurationForActivity,
} from "../store/page/selectors";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

interface ActivityReportedDurationOfNormProps {
	activityId: ActivityId;
}

const ActivityReportedDurationOfNorm: FC<ActivityReportedDurationOfNormProps> = (
	props,
) => {
	const {
		activityId,
	} = props;

	const reportedDurationForActivity = useApplicationSelector((
		state,
	) => {
		return selectReportedDurationForActivity(
			state.page,
			activityId,
		);
	});

	return (
		<ReportedDurationOfNorm
			location={`activity-info-cell-${activityId}`}
			reported={reportedDurationForActivity}
		/>
	);
};

export {
	ActivityReportedDurationOfNorm,
};

// solid/src/pages/signals/components/activity-reported-duration-of-norm.tsx
import {
	type Component,
} from "solid-js";

import {
	type ActivityId,
} from "@/features/activity/types";
import {
	type Duration,
} from "@/features/dates-and-time/types";

import {
	selectReportedDurationForActivity,
} from "../signals/page/derived";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

interface ActivityReportedDurationOfNormProps {
	activityId: ActivityId;
}

const ActivityReportedDurationOfNorm: Component<ActivityReportedDurationOfNormProps> = (
	props,
) => {
	const reportedDurationForActivity = (): Duration => {
		return selectReportedDurationForActivity(props.activityId);
	};

	return (
		<ReportedDurationOfNorm
			location={`activity-info-cell-${props.activityId}`}
			reported={reportedDurationForActivity()}
		/>
	);
};

export {
	ActivityReportedDurationOfNorm,
};
