// react/src/pages/redux/components/activity-row.tsx
import {
	type FC,
} from "react";

import {
	type Activity,
} from "@/features/activity/types";

import {
	ActivityInfoCell,
} from "./activity-info-cell";
import {
	Row,
} from "./row";
import {
	WorklogCells,
} from "./worklog-cells";

interface ActivityRowProps {
	activity: Activity;
}

const ActivityRow: FC<ActivityRowProps> = (
	props,
) => {
	const {
		activity,
	} = props;

	return (
		<Row>
			<ActivityInfoCell
				activity={activity}
			/>

			<WorklogCells
				activityId={activity.id}
				groupId={activity.groupId}
			/>
		</Row>
	);
};

export {
	ActivityRow,
};

// solid/src/pages/signals/components/activity-row.tsx
import {
	type Component,
} from "solid-js";

import {
	type Activity,
} from "@/features/activity/types";

import {
	ActivityInfoCell,
} from "./activity-info-cell";
import {
	Row,
} from "./row";
import {
	WorklogCells,
} from "./worklog-cells";

interface ActivityRowProps {
	activity: Activity;
}

const ActivityRow: Component<ActivityRowProps> = (
	props,
) => {
	return (
		<Row>
			<ActivityInfoCell
				activity={props.activity}
			/>

			<WorklogCells
				activityId={props.activity.id}
				groupId={props.activity.groupId}
			/>
		</Row>
	);
};

export {
	ActivityRow,
};
