// react/src/pages/redux/components/group-date-cell.tsx
import {
	type FC,
} from "react";

import {
	type DateString,
} from "@/features/dates-and-time/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectReportedDurationForGroupForDate,
} from "../store/page/selectors";
import {
	TotalDurationCell,
} from "./total-duration-cell";

interface GroupDateCellProps {
	groupId: GroupId;
	date: DateString;
}

const GroupDateCell: FC<GroupDateCellProps> = (
	props,
) => {
	const {
		groupId,
		date,
	} = props;

	const reportedDuration = useApplicationSelector((
		state,
	) => {
		return selectReportedDurationForGroupForDate(
			state.page,
			groupId,
			date,
		);
	});

	return (
		<TotalDurationCell
			date={date}
			duration={reportedDuration}
			location={`group-date-cell-${groupId}`}
		/>
	);
};

export {
	GroupDateCell,
};

// solid/src/pages/signals/components/group-date-cell.tsx
import {
	type Component,
} from "solid-js";

import {
	type DateString,
	type Duration,
} from "@/features/dates-and-time/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	selectReportedDurationForGroupForDate,
} from "../signals/page/derived";
import {
	TotalDurationCell,
} from "./total-duration-cell";

interface GroupDateCellProps {
	groupId: GroupId;
	date: DateString;
}

const GroupDateCell: Component<GroupDateCellProps> = (
	props,
) => {
	const reportedDuration = (): Duration => {
		return selectReportedDurationForGroupForDate(
			props.groupId,
			props.date,
		);
	};

	return (
		<TotalDurationCell
			date={props.date}
			duration={reportedDuration()}
			location={`group-date-cell-${props.groupId}`}
		/>
	);
};

export {
	GroupDateCell,
};
