// react/src/pages/redux/components/group-date-cells.tsx
import {
	type FC,
	Fragment,
} from "react";

import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectCalendar,
} from "../store/page/selectors";
import {
	GroupDateCell,
} from "./group-date-cell";

interface GroupDateCellsProps {
	groupId: GroupId;
}

const GroupDateCells: FC<GroupDateCellsProps> = (
	props,
) => {
	const {
		groupId,
	} = props;

	const calendar = useApplicationSelector((
		state,
	) => {
		return selectCalendar(state.page);
	});

	return (
		<Fragment>
			{
				calendar.map((
					calendarDay,
				) => {
					return (
						<GroupDateCell
							date={calendarDay.date}
							groupId={groupId}
							key={calendarDay.date}
						/>
					);
				})
			}
		</Fragment>
	);
};

export {
	GroupDateCells,
};

// solid/src/pages/signals/components/group-date-cells.tsx
import {
	type Component,
	For,
} from "solid-js";

import {
	type GroupId,
} from "@/features/group/types";

import {
	selectCalendar,
} from "../signals/page/derived";
import {
	GroupDateCell,
} from "./group-date-cell";

interface GroupDateCellsProps {
	groupId: GroupId;
}

const GroupDateCells: Component<GroupDateCellsProps> = (
	props,
) => {
	return (
		<For
			each={selectCalendar()}
		>
			{
				(
					calendarDay,
				) => {
					return (
						<GroupDateCell
							date={calendarDay.date}
							groupId={props.groupId}
						/>
					);
				}
			}
		</For>
	);
};

export {
	GroupDateCells,
};
