// react/src/pages/redux/components/group-name-input.tsx
import {
	type FC,
	useState,
} from "react";

import {
	FlexRow,
} from "@/components/flex-row";
import {
	GroupNameSchema,
} from "@/features/group/schemas";
import {
	type GroupId,
	type GroupName,
} from "@/features/group/types";

import {
	useApplicationDispatch,
} from "../store";
import {
	updateGroupName,
} from "../store/page/slice";
import {
	DuplicatedGroupNameIcon,
} from "./duplicated-group-name-icon";
import {
	NameInput,
} from "./name-input";

interface GroupNameInputProps {
	id: GroupId;
	name: GroupName;
}

const GroupNameInput: FC<GroupNameInputProps> = (
	props,
) => {
	const {
		id,
		name,
	} = props;

	const dispatch = useApplicationDispatch();

	const [
		nameLocal,
		setNameLocal,
	] = useState<string>(name);

	const handleBlur = (
		nameNext: GroupName,
	): void => {
		dispatch(
			updateGroupName({
				id,
				name: nameNext,
			}),
		);
	};

	return (
		<FlexRow
			className="gap-col-1"
		>
			<NameInput
				className="w-42"
				name={name}
				nameLocal={nameLocal}
				onBlur={handleBlur}
				placeholder="Group name"
				setNameLocal={setNameLocal}
				validationSchema={GroupNameSchema}
			/>

			<DuplicatedGroupNameIcon
				groupId={id}
				name={nameLocal}
			/>
		</FlexRow>
	);
};

export {
	GroupNameInput,
};

// solid/src/pages/signals/components/group-name-input.tsx
import {
	type Component,
	createEffect,
	createSignal,
} from "solid-js";

import {
	FlexRow,
} from "@/components/flex-row";
import {
	GroupNameSchema,
} from "@/features/group/schemas";
import {
	type GroupId,
	type GroupName,
} from "@/features/group/types";

import {
	updateGroupName,
} from "../utilities/update-group-name";
import {
	DuplicatedGroupNameIcon,
} from "./duplicated-group-name-icon";
import {
	NameInput,
} from "./name-input";

interface GroupNameInputProps {
	id: GroupId;
	name: GroupName;
}

const GroupNameInput: Component<GroupNameInputProps> = (
	props,
) => {
	const [
		nameLocal,
		setNameLocal,
	] = createSignal<string>("");

	createEffect(() => {
		setNameLocal(props.name);
	});

	const handleBlur = (
		nameNext: GroupName,
	): void => {
		updateGroupName({
			id: props.id,
			name: nameNext,
		});
	};

	return (
		<FlexRow
			class="gap-col-1"
		>
			<NameInput
				class="w-42"
				name={props.name}
				nameLocal={nameLocal()}
				onBlur={handleBlur}
				placeholder="Group name"
				setNameLocal={setNameLocal}
				validationSchema={GroupNameSchema}
			/>

			<DuplicatedGroupNameIcon
				groupId={props.id}
				name={nameLocal()}
			/>
		</FlexRow>
	);
};

export {
	GroupNameInput,
};
