// react/src/pages/redux/components/group-row.tsx
import {
	type FC,
} from "react";

import {
	type Group,
} from "@/features/group/types";

import {
	GroupDateCells,
} from "./group-date-cells";
import {
	GroupInfoCell,
} from "./group-info-cell";
import {
	Row,
} from "./row";

interface GroupRowProps {
	group: Group;
}

const GroupRow: FC<GroupRowProps> = (
	props,
) => {
	const {
		group,
	} = props;

	return (
		<Row>
			<GroupInfoCell
				group={group}
			/>

			<GroupDateCells
				groupId={group.id}
			/>
		</Row>
	);
};

export {
	GroupRow,
};

// solid/src/pages/signals/components/group-row.tsx
import {
	type Component,
} from "solid-js";

import {
	type Group,
} from "@/features/group/types";

import {
	GroupDateCells,
} from "./group-date-cells";
import {
	GroupInfoCell,
} from "./group-info-cell";
import {
	Row,
} from "./row";

interface GroupRowProps {
	group: Group;
}

const GroupRow: Component<GroupRowProps> = (
	props,
) => {
	return (
		<Row>
			<GroupInfoCell
				group={props.group}
			/>

			<GroupDateCells
				groupId={props.group.id}
			/>
		</Row>
	);
};

export {
	GroupRow,
};
