// react/src/pages/redux/components/page-leave-blocker.tsx
import {
	type FC,
} from "react";

import {
	PageLeaveBlocker as PageLeaveBlockerCommon,
} from "@/components/page-leave-blocker";

import {
	useApplicationSelector,
} from "../store";
import {
	selectHasChanges,
} from "../store/page/selectors";

const PageLeaveBlocker: FC = () => {
	const hasChanges = useApplicationSelector((
		state,
	) => {
		return selectHasChanges(state.page);
	});

	return (
		<PageLeaveBlockerCommon
			hasChanges={hasChanges}
		/>
	);
};

export {
	PageLeaveBlocker,
};

// solid/src/pages/signals/components/page-leave-blocker.tsx
import {
	type Component,
} from "solid-js";

import {
	PageLeaveBlocker as PageLeaveBlockerCommon,
} from "@/components/page-leave-blocker";

import {
	selectHasChanges,
} from "../signals/page/derived";

const PageLeaveBlocker: Component = () => {
	return (
		<PageLeaveBlockerCommon
			hasChanges={selectHasChanges()}
		/>
	);
};

export {
	PageLeaveBlocker,
};
