// react/src/pages/redux/components/remove-activity-button.tsx
import {
	type FC,
} from "react";

import {
	Tooltip,
} from "@/components/tooltip";
import {
	type ActivityId,
} from "@/features/activity/types";
import {
	useIsBusy,
} from "@/hooks/use-is-busy";
import {
	getClass,
} from "@/utilities/get-class";

import {
	useApplicationDispatch,
} from "../store";
import {
	removeActivity,
} from "../store/page/slice";

interface RemoveActivityButtonProps {
	activityId: ActivityId;
}

const RemoveActivityButton: FC<RemoveActivityButtonProps> = ({
	activityId,
}) => {
	const dispatch = useApplicationDispatch();

	const isBusy = useIsBusy();

	const handleRemoveActivity = (): void => {
		dispatch(removeActivity(activityId));
	};

	return (
		<Tooltip<HTMLButtonElement>
			renderBody={() => {
				return "Remove activity and its worklogs";
			}}
			renderTarget={({
				className,
				tooltipId,
				...targetProps
			}) => {
				return (
					<button
						{...targetProps}
						aria-describedby={tooltipId}
						className={
							getClass([
								className,
								"control icon-button",
							])
						}
						disabled={isBusy}
						onClick={handleRemoveActivity}
						type="button"
					>
						-
					</button>
				);
			}}
			targetId={`remove-activity-button-${activityId}`}
		/>
	);
};

export {
	RemoveActivityButton,
};

// solid/src/pages/signals/components/remove-activity-button.tsx
import {
	type Component,
} from "solid-js";

import {
	Tooltip,
} from "@/components/tooltip";
import {
	type ActivityId,
} from "@/features/activity/types";
import {
	useIsBusy,
} from "@/hooks/use-is-busy";
import {
	getClass,
} from "@/utilities/get-class";

import {
	removeActivity,
} from "../utilities/remove-activity";

interface RemoveActivityButtonProps {
	activityId: ActivityId;
}

const RemoveActivityButton: Component<RemoveActivityButtonProps> = (
	props,
) => {
	const isBusy = useIsBusy();

	const handleRemoveActivity = (): void => {
		removeActivity(props.activityId);
	};

	return (
		<Tooltip<HTMLButtonElement>
			renderBody={() => {
				return "Remove activity and its worklogs";
			}}
			renderTarget={(
				targetProps,
			) => {
				return (
					<button
						{...targetProps}
						aria-describedby={targetProps.popoverTarget}
						class={
							getClass([
								targetProps.class,
								"control icon-button",
							])
						}
						disabled={isBusy()}
						onClick={handleRemoveActivity}
						type="button"
					>
						-
					</button>
				);
			}}
			targetId={`remove-activity-button-${props.activityId}`}
		/>
	);
};

export {
	RemoveActivityButton,
};
