// react/src/pages/redux/components/select-groups-checkbox.tsx
import {
	type FC,
} from "react";

import {
	SelectEntityCheckbox,
} from "@/components/select-entity-checkbox";

import {
	useApplicationDispatch,
	useApplicationSelector,
} from "../store";
import {
	selectHasWorklogs,
	selectSelectionStateForGroups,
} from "../store/page/selectors";
import {
	updateAllWorklogsSelection,
} from "../utilities/update-all-worklogs-selection";

const SelectGroupsCheckbox: FC = () => {
	const dispatch = useApplicationDispatch();

	const selectionState = useApplicationSelector((
		state,
	) => {
		return selectSelectionStateForGroups(state.page);
	});
	const hasWorklogs = useApplicationSelector((
		state,
	) => {
		return selectHasWorklogs(state.page);
	});

	const handleSelectionChange = (
		isSelectedNext: boolean,
	): void => {
		dispatch(
			updateAllWorklogsSelection({
				isSelected: isSelectedNext,
			}),
		);
	};

	return (
		<SelectEntityCheckbox
			isDisabled={!hasWorklogs}
			onSelectionChange={handleSelectionChange}
			selectionState={selectionState}
		/>
	);
};

export {
	SelectGroupsCheckbox,
};

// solid/src/pages/signals/components/select-groups-checkbox.tsx
import {
	type Component,
} from "solid-js";

import {
	SelectEntityCheckbox,
} from "@/components/select-entity-checkbox";

import {
	selectHasWorklogs,
	selectSelectionStateForGroups,
} from "../signals/page/derived";
import {
	updateAllWorklogsSelection,
} from "../utilities/update-all-worklogs-selection";

const handleSelectionChange = (
	isSelectedNext: boolean,
): void => {
	updateAllWorklogsSelection({
		isSelected: isSelectedNext,
	});
};

const SelectGroupsCheckbox: Component = () => {
	return (
		<SelectEntityCheckbox
			isDisabled={!selectHasWorklogs()}
			onSelectionChange={handleSelectionChange}
			selectionState={selectSelectionStateForGroups()}
		/>
	);
};

export {
	SelectGroupsCheckbox,
};
