// react/src/pages/redux/components/summary-row.tsx
import {
	type FC,
} from "react";

import {
	Row,
} from "./row";
import {
	SummaryDateCells,
} from "./summary-date-cells";
import {
	SummaryInfoCell,
} from "./summary-info-cell";

const SummaryRow: FC = () => {
	return (
		<Row>
			<SummaryInfoCell/>
			<SummaryDateCells/>
		</Row>
	);
};

export {
	SummaryRow,
};

// solid/src/pages/signals/components/summary-row.tsx
import {
	type Component,
} from "solid-js";

import {
	Row,
} from "./row";
import {
	SummaryDateCells,
} from "./summary-date-cells";
import {
	SummaryInfoCell,
} from "./summary-info-cell";

const SummaryRow: Component = () => {
	return (
		<Row>
			<SummaryInfoCell/>
			<SummaryDateCells/>
		</Row>
	);
};

export {
	SummaryRow,
};
