// react/src/pages/redux/components/summary-date-cells.tsx
import {
	type FC,
	Fragment,
} from "react";

import {
	useApplicationSelector,
} from "../store";
import {
	selectCalendar,
} from "../store/page/selectors";
import {
	SummaryDateCell,
} from "./summary-date-cell";

const SummaryDateCells: FC = () => {
	const calendar = useApplicationSelector((state) => {
		return selectCalendar(state.page);
	});

	return (
		<Fragment>
			{
				calendar.map((calendarDay) => {
					return (
						<SummaryDateCell
							date={calendarDay.date}
							key={calendarDay.date}
						/>
					);
				})
			}
		</Fragment>
	);
};

export {
	SummaryDateCells,
};

// solid/src/pages/signals/components/summary-date-cells.tsx
import {
	type Component,
	For,
} from "solid-js";

import {
	selectCalendar,
} from "../signals/page/derived";
import {
	SummaryDateCell,
} from "./summary-date-cell";

const SummaryDateCells: Component = () => {
	return (
		<For
			each={selectCalendar()}
		>
			{
				(
					calendarDay,
				) => {
					return (
						<SummaryDateCell
							date={calendarDay.date}
						/>
					);
				}
			}
		</For>
	);
};

export {
	SummaryDateCells,
};
