// react/src/pages/redux/components/summary-date-cell.tsx
import {
	type FC,
} from "react";

import {
	type DateString,
} from "@/features/dates-and-time/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectReportedDurationForDate,
} from "../store/page/selectors";
import {
	TotalDurationCell,
} from "./total-duration-cell";

interface SummaryDateCellProps {
	date: DateString;
}

const SummaryDateCell: FC<SummaryDateCellProps> = (
	props,
) => {
	const {
		date,
	} = props;

	const reportedDuration = useApplicationSelector((
		state,
	) => {
		return selectReportedDurationForDate(
			state.page,
			date,
		);
	});

	return (
		<TotalDurationCell
			date={date}
			duration={reportedDuration}
			location="summary-date-cell"
		/>
	);
};

export {
	SummaryDateCell,
};

// solid/src/pages/signals/components/summary-date-cell.tsx
import {
	type Component,
} from "solid-js";

import {
	type DateString,
	type Duration,
} from "@/features/dates-and-time/types";

import {
	selectReportedDurationForDate,
} from "../signals/page/derived";
import {
	TotalDurationCell,
} from "./total-duration-cell";

interface SummaryDateCellProps {
	date: DateString;
}

const SummaryDateCell: Component<SummaryDateCellProps> = (
	props,
) => {
	const reportedDuration = (): Duration => {
		return selectReportedDurationForDate(props.date);
	};

	return (
		<TotalDurationCell
			date={props.date}
			duration={reportedDuration()}
			location="summary-date-cell"
		/>
	);
};

export {
	SummaryDateCell,
};
