// solid/src/pages/signals/components/activity-rows.tsx
import {
	type Component,
	For,
} from "solid-js";

import {
	type Activity,
} from "@/features/activity/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	selectActivitiesForGroup,
} from "../signals/page/derived";
import {
	ActivityRow,
} from "./activity-row";

interface ActivityRowsProps {
	groupId: GroupId;
}

const ActivityRows: Component<ActivityRowsProps> = (
	props,
) => {
	const activities = (): Array<Activity> => {
		return selectActivitiesForGroup(props.groupId);
	};

	return (
		<For
			each={activities()}
		>
			{
				(
					activity,
				) => {
					return (
						<ActivityRow
							activity={activity}
						/>
					);
				}
			}
		</For>
	);
};

export {
	ActivityRows,
};

// react/src/pages/redux/components/activity-rows.tsx
import {
	type FC,
	Fragment,
} from "react";

import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectActivitiesForGroup,
} from "../store/page/selectors";
import {
	ActivityRow,
} from "./activity-row";

interface ActivityRowsProps {
	groupId: GroupId;
}

const ActivityRows: FC<ActivityRowsProps> = ({
	groupId,
}) => {
	const activities = useApplicationSelector((state) => {
		return selectActivitiesForGroup(
			state.page,
			groupId,
		);
	});

	return (
		<Fragment>
			{
				activities.map((activity) => {
					return (
						<ActivityRow
							activity={activity}
							key={activity.id}
						/>
					);
				})
			}
		</Fragment>
	);
};

export {
	ActivityRows,
};
