// solid/src/pages/signals/components/cell.tsx
import {
	type Component,
	type ComponentProps,
} from "solid-js";

import {
	type DateString,
} from "@/features/dates-and-time/types";
import {
	getIsWeekend,
} from "@/features/dates-and-time/utilities/get-is-weekend";
import {
	getClass,
} from "@/utilities/get-class";
import {
	isUndefined,
} from "@/utilities/is-undefined";

interface CellProps extends ComponentProps<"td"> {
	date?: DateString;
}

const Cell: Component<CellProps> = (
	props,
) => {
	const isDateCell = (): boolean => {
		return !isUndefined(props.date);
	};

	return (
		<td
			{...props}
			class={
				getClass([
					"cell",
					[
						isDateCell(),
						"bg-gray-50",
					],
					[
						(
							isDateCell()
							// @ts-expect-error `undefined` is checked in `isDateCell`.
							&& getIsWeekend(props.date)
						),
						"bg-weekend",
					],
					props.class,
				])
			}
		/>
	);
};

export {
	Cell,
};

// react/src/pages/redux/components/cell.tsx
import {
	type ComponentProps,
	type FC,
} from "react";

import {
	type DateString,
} from "@/features/dates-and-time/types";
import {
	getIsWeekend,
} from "@/features/dates-and-time/utilities/get-is-weekend";
import {
	getClass,
} from "@/utilities/get-class";
import {
	isUndefined,
} from "@/utilities/is-undefined";

interface CellProps extends ComponentProps<"td"> {
	date?: DateString;
}

const Cell: FC<CellProps> = (
	props,
) => {
	const {
		className,
		date,
	} = props;

	const isDateCell = !isUndefined(date);

	return (
		<td
			{...props}
			className={
				getClass([
					"cell",
					[
						isDateCell,
						"bg-gray-50",
					],
					[
						(
							isDateCell
							&& getIsWeekend(date)
						),
						"bg-weekend",
					],
					className,
				])
			}
		/>
	);
};

export {
	Cell,
};
