// solid/src/pages/signals/components/group-reported-duration-of-norm.tsx
import {
	type Component,
} from "solid-js";

import {
	type Duration,
} from "@/features/dates-and-time/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	selectReportedDurationForGroup,
} from "../signals/page/derived";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

interface GroupReportedDurationOfNormProps {
	groupId: GroupId;
}

const GroupReportedDurationOfNorm: Component<GroupReportedDurationOfNormProps> = (
	props,
) => {
	const reportedDurationForGroup = (): Duration => {
		return selectReportedDurationForGroup(props.groupId);
	};

	return (
		<ReportedDurationOfNorm
			location={`group-info-cell-${props.groupId}`}
			reported={reportedDurationForGroup()}
		/>
	);
};

export {
	GroupReportedDurationOfNorm,
};

// react/src/pages/redux/components/group-reported-duration-of-norm.tsx
import {
	type FC,
} from "react";

import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectReportedDurationForGroup,
} from "../store/page/selectors";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

interface GroupReportedDurationOfNormProps {
	groupId: GroupId;
}

const GroupReportedDurationOfNorm: FC<GroupReportedDurationOfNormProps> = ({
	groupId,
}) => {
	const reportedDurationForGroup = useApplicationSelector((state) => {
		return selectReportedDurationForGroup(
			state.page,
			groupId,
		);
	});

	return (
		<ReportedDurationOfNorm
			location={`group-info-cell-${groupId}`}
			reported={reportedDurationForGroup}
		/>
	);
};

export {
	GroupReportedDurationOfNorm,
};
