// solid/src/pages/signals/components/header-row.tsx
import {
	type Component,
} from "solid-js";

import {
	HeaderDateCells,
} from "./header-date-cells";
import {
	HeaderInfoCell,
} from "./header-info-cell";
import {
	Row,
} from "./row";

const HeaderRow: Component = () => {
	return (
		<Row>
			<HeaderInfoCell/>
			<HeaderDateCells/>
		</Row>
	);
};

export {
	HeaderRow,
};

// react/src/pages/redux/components/header-row.tsx
import {
	type FC,
} from "react";

import {
	HeaderDateCells,
} from "./header-date-cells";
import {
	HeaderInfoCell,
} from "./header-info-cell";
import {
	Row,
} from "./row";

const HeaderRow: FC = () => {
	return (
		<Row>
			<HeaderInfoCell/>
			<HeaderDateCells/>
		</Row>
	);
};

export {
	HeaderRow,
};
