// solid/src/pages/signals/components/header-date-cells.tsx
import {
	type Component,
	For,
} from "solid-js";

import {
	selectCalendar,
} from "../signals/page/derived";
import {
	HeaderDateCell,
} from "./header-date-cell";

const HeaderDateCells: Component = () => {
	return (
		<For
			each={selectCalendar()}
		>
			{
				(
					calendarDay,
				) => {
					return (
						<HeaderDateCell
							date={calendarDay.date}
						/>
					);
				}
			}
		</For>
	);
};

export {
	HeaderDateCells,
};

// react/src/pages/redux/components/header-date-cells.tsx
import {
	type FC,
	Fragment,
} from "react";

import {
	useApplicationSelector,
} from "../store";
import {
	selectCalendar,
} from "../store/page/selectors";
import {
	HeaderDateCell,
} from "./header-date-cell";

const HeaderDateCells: FC = () => {
	const calendar = useApplicationSelector((
		state,
	) => {
		return selectCalendar(state.page);
	});

	return (
		<Fragment>
			{
				calendar.map((
					calendarDay,
				) => {
					return (
						<HeaderDateCell
							date={calendarDay.date}
							key={calendarDay.date}
						/>
					);
				})
			}
		</Fragment>
	);
};

export {
	HeaderDateCells,
};
