// solid/src/pages/components/page-actions-row.tsx
import {
	type Component,
} from "solid-js";

import {
	FlexRow,
} from "@/components/flex-row";

import {
	SaveChangesButton,
} from "./save-changes-button";

const PageActionsRow: Component = () => {
	return (
		<FlexRow
			class="gap-col-2"
		>
			<SaveChangesButton/>
		</FlexRow>
	);
};

export {
	PageActionsRow,
};

// react/src/pages/redux/components/page-actions-row.tsx
import {
	type FC,
} from "react";

import {
	FlexRow,
} from "@/components/flex-row";

import {
	SaveChangesButton,
} from "./save-changes-button";

const PageActionsRow: FC = () => {
	return (
		<FlexRow
			className="gap-col-2"
		>
			<SaveChangesButton/>
		</FlexRow>
	);
};

export {
	PageActionsRow,
};
