// solid/src/pages/components/save-changes-button.tsx
import {
	useMutation,
	useQueryClient,
} from "@tanstack/solid-query";
import {
	type Component,
	splitProps,
} from "solid-js";

import {
	Tooltip,
} from "@/components/tooltip";
import {
	QUERY_KEYS,
} from "@/constants";
import {
	useIsBusy,
} from "@/hooks/use-is-busy";
import {
	getClass,
} from "@/utilities/get-class";

import {
	hasChanges,
} from "../signals/signals/page/derived";
import {
	savePageState,
} from "../utilities/save-page-state";

const SaveChangesButton: Component = () => {
	const queryClient = useQueryClient();

	const saveChangesMutation = useMutation(() => {
		return {
			mutationFn: async () => {
				await savePageState();
			},
			onSuccess: async () => {
				await queryClient.invalidateQueries({
					queryKey: [
						QUERY_KEYS.PAGE_DATA,
					],
				});
			},
		};
	});

	const isBusy = useIsBusy();

	return (
		<Tooltip<HTMLButtonElement>
			renderBody={() => {
				return "Save changes to Local Storage";
			}}
			renderTarget={(
				targetProps,
			) => {
				const [
					props,
					otherTargetProps,
				] = splitProps(
					targetProps,
					[
						"class",
						"tooltipId",
					],
				);

				return (
					<button
						{...otherTargetProps}
						aria-describedby={props.tooltipId}
						class={
							getClass([
								props.class,
								"control",
							])
						}
						disabled={
							!hasChanges()
							|| isBusy()
						}
						onClick={() => {
							saveChangesMutation.mutate();
						}}
						type="button"
					>
						Save changes
					</button>
				);
			}}
			targetId="save-changes-button"
		/>
	);
};

export {
	SaveChangesButton,
};

// react/src/pages/redux/components/save-changes-button.tsx
import {
	useMutation,
	useQueryClient,
} from "@tanstack/react-query";
import {
	type FC,
} from "react";

import {
	Tooltip,
} from "@/components/tooltip";
import {
	QUERY_KEYS,
} from "@/constants";
import {
	useIsBusy,
} from "@/hooks/use-is-busy";
import {
	getClass,
} from "@/utilities/get-class";

import {
	useApplicationDispatch,
	useApplicationSelector,
} from "../store";
import {
	selectHasChanges,
} from "../store/page/selectors";
import {
	savePageState,
} from "../utilities/save-page-state";

const SaveChangesButton: FC = () => {
	const dispatch = useApplicationDispatch();

	const hasChanges = useApplicationSelector((
		state,
	) => {
		return selectHasChanges(state.page);
	});

	const queryClient = useQueryClient();

	const {
		mutate: handleSaveChanges,
	} = useMutation({
		mutationFn: async () => {
			await dispatch(savePageState());
		},
		onSuccess: async () => {
			await queryClient.invalidateQueries({
				queryKey: [
					QUERY_KEYS.PAGE_DATA,
				],
			});
		},
	});

	const isBusy = useIsBusy();

	return (
		<Tooltip<HTMLButtonElement>
			renderBody={() => {
				return "Save changes to Local Storage";
			}}
			renderTarget={(
				targetProps,
			) => {
				const {
					className,
					tooltipId,
					...otherTargetProps
				} = targetProps;

				return (
					<button
						{...otherTargetProps}
						aria-describedby={tooltipId}
						className={
							getClass([
								className,
								"control",
							])
						}
						disabled={
							!hasChanges
							|| isBusy
						}
						onClick={() => {
							handleSaveChanges();
						}}
						type="button"
					>
						Save changes
					</button>
				);
			}}
			targetId="save-changes-button"
		/>
	);
};

export {
	SaveChangesButton,
};
