// solid/src/pages/signals/components/select-group-checkbox.tsx
import {
	type Component,
} from "solid-js";

import {
	SelectEntityCheckbox,
} from "@/components/select-entity-checkbox";
import {
	type GroupId,
} from "@/features/group/types";
import {
	type EntitySelectionState,
} from "@/features/page/types";

import {
	selectHasWorklogsInGroup,
	selectSelectionStateForGroup,
} from "../signals/page/derived";
import {
	updateWorklogsSelectionForGroup,
} from "../utilities/update-worklogs-selection-for-group";

interface SelectGroupCheckboxProps {
	groupId: GroupId;
}

const SelectGroupCheckbox: Component<SelectGroupCheckboxProps> = (
	props,
) => {
	const selectionState = (): EntitySelectionState => {
		return selectSelectionStateForGroup(props.groupId);
	};

	const hasWorklogs = (): boolean => {
		return selectHasWorklogsInGroup(props.groupId);
	};

	const handleSelectionChange = (
		isSelectedNext: boolean,
	): void => {
		updateWorklogsSelectionForGroup({
			groupId: props.groupId,
			isSelected: isSelectedNext,
		});
	};

	return (
		<SelectEntityCheckbox
			isDisabled={!hasWorklogs()}
			onSelectionChange={handleSelectionChange}
			selectionState={selectionState()}
		/>
	);
};

export {
	SelectGroupCheckbox,
};

// react/src/pages/redux/components/select-group-checkbox.tsx
import {
	type FC,
} from "react";

import {
	SelectEntityCheckbox,
} from "@/components/select-entity-checkbox";
import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationDispatch,
	useApplicationSelector,
} from "../store";
import {
	selectHasWorklogsInGroup,
	selectSelectionStateForGroup,
} from "../store/page/selectors";
import {
	updateWorklogsSelectionForGroup,
} from "../utilities/update-worklogs-selection-for-group";

interface SelectGroupCheckboxProps {
	groupId: GroupId;
}

const SelectGroupCheckbox: FC<SelectGroupCheckboxProps> = ({
	groupId,
}) => {
	const dispatch = useApplicationDispatch();

	const selectionState = useApplicationSelector((state) => {
		return selectSelectionStateForGroup(
			state.page,
			groupId,
		);
	});
	const hasWorklogs = useApplicationSelector((state) => {
		return selectHasWorklogsInGroup(
			state.page,
			groupId,
		);
	});

	const handleSelectionChange = (
		isSelectedNext: boolean,
	): void => {
		dispatch(
			updateWorklogsSelectionForGroup({
				groupId,
				isSelected: isSelectedNext,
			}),
		);
	};

	return (
		<SelectEntityCheckbox
			isDisabled={!hasWorklogs}
			onSelectionChange={handleSelectionChange}
			selectionState={selectionState}
		/>
	);
};

export {
	SelectGroupCheckbox,
};
