// solid/src/pages/signals/components/summary-reported-duration-of-norm.tsx
import {
	type Component,
} from "solid-js";

import {
	selectReportedDuration,
} from "../signals/page/derived";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

const SummaryReportedDurationOfNorm: Component = () => {
	return (
		<ReportedDurationOfNorm
			location="summary-info-cell"
			reported={selectReportedDuration()}
		/>
	);
};

export {
	SummaryReportedDurationOfNorm,
};

// react/src/pages/redux/components/summary-reported-duration-of-norm.tsx
import {
	type FC,
} from "react";

import {
	useApplicationSelector,
} from "../store";
import {
	selectReportedDuration,
} from "../store/page/selectors";
import {
	ReportedDurationOfNorm,
} from "./reported-duration-of-norm";

const SummaryReportedDurationOfNorm: FC = () => {
	const reportedDuration = useApplicationSelector((state) => {
		return selectReportedDuration(state.page);
	});

	return (
		<ReportedDurationOfNorm
			location="summary-info-cell"
			reported={reportedDuration}
		/>
	);
};

export {
	SummaryReportedDurationOfNorm,
};
