// solid/src/pages/signals/components/table.tsx
import {
	type Component,
	type ComponentProps,
	Show,
} from "solid-js";

import {
	getClass,
} from "@/utilities/get-class";
import {
	isEmpty,
} from "@/utilities/is-empty";

import {
	selectCalendar,
} from "../signals/page/derived";
import {
	GroupRows,
} from "./group-rows";
import {
	HeaderRow,
} from "./header-row";
import {
	SummaryRow,
} from "./summary-row";

const isCalendarEmpty = (): boolean => {
	return isEmpty(selectCalendar());
};

type TableProps = ComponentProps<"table">;

const Table: Component<TableProps> = (
	props,
) => {
	return (
		<Show
			fallback={null}
			when={!isCalendarEmpty()}
		>
			<table
				class={
					getClass([
						props.class,
						"w-full b-collapse",
					])
				}
			>
				<thead>
					<HeaderRow/>
				</thead>

				<tbody>
					<SummaryRow/>
					<GroupRows/>
				</tbody>
			</table>
		</Show>
	);
};

export {
	Table,
};

// react/src/pages/redux/components/table.tsx
import {
	type ComponentProps,
	type FC,
} from "react";

import {
	getClass,
} from "@/utilities/get-class";
import {
	isEmpty,
} from "@/utilities/is-empty";

import {
	useApplicationSelector,
} from "../store";
import {
	selectCalendar,
} from "../store/page/selectors";
import {
	GroupRows,
} from "./group-rows";
import {
	HeaderRow,
} from "./header-row";
import {
	SummaryRow,
} from "./summary-row";

type TableProps = ComponentProps<"table">;

const Table: FC<TableProps> = ({
	className,
}) => {
	const calendar = useApplicationSelector((state) => {
		return selectCalendar(state.page);
	});

	if (isEmpty(calendar)) {
		return null;
	}

	return (
		<table
			className={
				getClass([
					className,
					"w-full b-collapse",
				])
			}
		>
			<thead>
				<HeaderRow/>
			</thead>

			<tbody>
				<SummaryRow/>
				<GroupRows/>
			</tbody>
		</table>
	);
};

export {
	Table,
};
