// solid/src/pages/signals/components/total-duration.tsx
import {
	type Component,
	mergeProps,
	Show,
} from "solid-js";

import {
	type Duration,
} from "@/features/dates-and-time/types";
import {
	formatDuration,
} from "@/features/dates-and-time/utilities/format-duration";

interface TotalDurationProps {
	class?: string;
	duration: Duration;
	shouldRenderZero?: boolean;
}

const TotalDuration: Component<TotalDurationProps> = (
	props,
) => {
	const mergedProps = mergeProps(
		{
			shouldRenderZero: false,
		},
		props,
	);

	return (
		<Show
			fallback={null}
			when={
				mergedProps.duration !== 0
				|| mergedProps.shouldRenderZero
			}
		>
			<span
				class={mergedProps.class}
			>
				{formatDuration(mergedProps.duration)}
			</span>
		</Show>
	);
};

export {
	TotalDuration,
};

// react/src/pages/redux/components/total-duration.tsx
import {
	type FC,
} from "react";

import {
	type Duration,
} from "@/features/dates-and-time/types";
import {
	formatDuration,
} from "@/features/dates-and-time/utilities/format-duration";

interface TotalDurationProps {
	className?: string;
	duration: Duration;
	shouldRenderZero?: boolean;
}

const TotalDuration: FC<TotalDurationProps> = (
	props,
) => {
	const {
		className,
		duration,
		shouldRenderZero = false,
	} = props;

	if (
		duration === 0
		&& !shouldRenderZero
	) {
		return null;
	}

	return (
		<span
			className={className}
		>
			{formatDuration(duration)}
		</span>
	);
};

export {
	TotalDuration,
};
