// solid/src/pages/signals/components/worklog-cells.tsx
import {
	type Component,
	For,
} from "solid-js";

import {
	type ActivityId,
} from "@/features/activity/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	selectCalendar,
} from "../signals/page/derived";
import {
	WorklogCell,
} from "./worklog-cell";

interface WorklogCellsProps {
	activityId: ActivityId;
	groupId: GroupId;
}

const WorklogCells: Component<WorklogCellsProps> = (
	props,
) => {
	return (
		<For
			each={selectCalendar()}
		>
			{
				(
					calendarDay,
				) => {
					return (
						<WorklogCell
							activityId={props.activityId}
							date={calendarDay.date}
							groupId={props.groupId}
							norm={calendarDay.norm}
						/>
					);
				}
			}
		</For>
	);
};

export {
	WorklogCells,
};

// react/src/pages/redux/components/worklog-cells.tsx
import {
	type FC,
	Fragment,
} from "react";

import {
	type ActivityId,
} from "@/features/activity/types";
import {
	type GroupId,
} from "@/features/group/types";

import {
	useApplicationSelector,
} from "../store";
import {
	selectCalendar,
} from "../store/page/selectors";
import {
	WorklogCell,
} from "./worklog-cell";

interface WorklogCellsProps {
	activityId: ActivityId;
	groupId: GroupId;
}

const WorklogCells: FC<WorklogCellsProps> = ({
	activityId,
	groupId,
}) => {
	const calendar = useApplicationSelector((state) => {
		return selectCalendar(state.page);
	});

	return (
		<Fragment>
			{
				calendar.map((calendarDay) => {
					return (
						<WorklogCell
							activityId={activityId}
							date={calendarDay.date}
							groupId={groupId}
							key={calendarDay.date}
							norm={calendarDay.norm}
						/>
					);
				})
			}
		</Fragment>
	);
};

export {
	WorklogCells,
};
