// solid/src/components/flex-column.tsx
import {
	type Component,
	type ComponentProps,
} from "solid-js";

import {
	getClass,
} from "@/utilities/get-class";

type FlexColumnProps = ComponentProps<"div">;

const FlexColumn: Component<FlexColumnProps> = (
	props,
) => {
	return (
		<div
			{...props}
			class={
				getClass([
					props.class,
					"flex flex-col",
				])
			}
		/>
	);
};

export {
	FlexColumn,
};

// react/src/components/flex-column.tsx
import {
	type ComponentProps,
	type FC,
} from "react";

import {
	getClass,
} from "@/utilities/get-class";

type FlexColumnProps = ComponentProps<"div">;

const FlexColumn: FC<FlexColumnProps> = (
	props,
) => {
	const {
		className,
	} = props;

	return (
		<div
			{...props}
			className={
				getClass([
					className,
					"flex flex-col",
				])
			}
		/>
	);
};

export {
	FlexColumn,
};
