// solid/src/components/flex-row.tsx
import {
	type Component,
	type ComponentProps,
} from "solid-js";

import {
	getClass,
} from "@/utilities/get-class";

type FlexRowProps = ComponentProps<"div">;

const FlexRow: Component<FlexRowProps> = (
	props,
) => {
	return (
		<div
			{...props}
			class={
				getClass([
					props.class,
					"flex flex-items-center",
				])
			}
		/>
	);
};

export {
	FlexRow,
};

// react/src/components/flex-row.tsx
import {
	type ComponentProps,
	type FC,
} from "react";

import {
	getClass,
} from "@/utilities/get-class";

type FlexRowProps = ComponentProps<"div">;

const FlexRow: FC<FlexRowProps> = (props) => {
	const {
		className,
	} = props;

	return (
		<div
			{...props}
			className={
				getClass([
					className,
					"flex flex-items-center",
				])
			}
		/>
	);
};

export {
	FlexRow,
};
