// solid/src/components/tooltip.tsx
import {
	type Accessor,
	createEffect,
	createSignal,
	type JSX,
	type Setter,
} from "solid-js";

import {
	getClass,
} from "@/utilities/get-class";
import {
	isNull,
} from "@/utilities/is-null";

import css from "./tooltip.module.css";

interface RenderTargetProps<TargetElement extends HTMLElement> {
	class: string | undefined;
	id: string;
	onBlur: () => void;
	onFocus: () => void;
	onMouseEnter: () => void;
	onMouseLeave: () => void;
	popoverTarget: string;
	ref: Setter<TargetElement | null>;
	tabIndex: number;
	tooltipId: string;
}

interface TooltipProps<TargetElement extends HTMLElement> {
	renderBody: () => JSX.Element;
	renderTarget: (
		props: RenderTargetProps<TargetElement>,
	) => JSX.Element;
	targetId: string;
}

const Tooltip = <TargetElement extends HTMLElement>(
	props: TooltipProps<TargetElement>,
): JSX.Element => {
	const [
		targetRef,
		setTargetRef,
	] = createSignal<TargetElement | null>(null);
	const [
		tooltipRef,
		setTooltipRef,
	] = createSignal<HTMLDivElement | null>(null);

	const showTooltip = (): void => {
		tooltipRef()?.showPopover();
	};

	const hideTooltip = (): void => {
		tooltipRef()?.hidePopover();
	};

	const tooltipId: Accessor<string> = () => {
		return `${props.targetId}-tooltip`;
	};

	createEffect(() => {
		const target = targetRef();

		if (!isNull(target)) {
			target.setAttribute(
				"style",
				`--anchor-name: --${props.targetId}`,
			);
		}
	});

	return (
		<>
			{
				props.renderTarget({
					class: css.target,
					id: props.targetId,
					onBlur: hideTooltip,
					onFocus: showTooltip,
					onMouseEnter: showTooltip,
					onMouseLeave: hideTooltip,
					popoverTarget: tooltipId(),
					ref: setTargetRef,
					tabIndex: 0,
					tooltipId: tooltipId(),
				})
			}

			<div
				class={
					getClass([
						css.tooltip,
						"m-0 m-block-1 max-w-64 b-1px b-solid p-2",
					])
				}
				id={tooltipId()}
				popover="auto"
				ref={setTooltipRef}
				role="tooltip"
				style={{
					"--anchor-name": `--${props.targetId}`,
				}}
			>
				{props.renderBody()}
			</div>
		</>
	);
};

export {
	Tooltip,
};

// react/src/components/tooltip.tsx
import {
	type CSSProperties,
	Fragment,
	type ReactNode,
	type RefObject,
	useLayoutEffect,
	useRef,
} from "react";

import {
	getClass,
} from "@/utilities/get-class";
import {
	isNull,
} from "@/utilities/is-null";

import css from "./tooltip.module.css";

interface RenderTargetProps<TargetElement extends HTMLElement> {
	className: string | undefined;
	id: string;
	onBlur: () => void;
	onFocus: () => void;
	onMouseEnter: () => void;
	onMouseLeave: () => void;
	popoverTarget: string;
	ref: RefObject<TargetElement | null>;
	tabIndex: number;
	tooltipId: string;
}

interface TooltipProps<TargetElement extends HTMLElement> {
	renderBody: () => ReactNode;
	renderTarget: (
		props: RenderTargetProps<TargetElement>,
	) => ReactNode;
	targetId: string;
}

const Tooltip = <TargetElement extends HTMLElement>({
	renderBody,
	renderTarget,
	targetId,
}: TooltipProps<TargetElement>): ReactNode => {
	const targetRef = useRef<TargetElement | null>(null);
	const tooltipRef = useRef<HTMLDivElement | null>(null);

	const showTooltip = (): void => {
		tooltipRef.current?.showPopover();
	};

	const hideTooltip = (): void => {
		tooltipRef.current?.hidePopover();
	};

	const tooltipId = `${targetId}-tooltip`;

	useLayoutEffect(
		() => {
			if (!isNull(targetRef.current)) {
				targetRef.current.setAttribute(
					"style",
					`--anchor-name: --${targetId}`,
				);
			}
		},
		[
			targetId,
		],
	);

	return (
		<Fragment>
			{
				renderTarget({
					className: css.target,
					id: targetId,
					onBlur: hideTooltip,
					onFocus: showTooltip,
					onMouseEnter: showTooltip,
					onMouseLeave: hideTooltip,
					popoverTarget: tooltipId,
					ref: targetRef,
					tabIndex: 0,
					tooltipId,
				})
			}

			<div
				className={
					getClass([
						css.tooltip,
						"m-0 m-block-1 max-w-64 b-1px b-solid p-2",
					])
				}
				id={tooltipId}
				popover="auto"
				ref={tooltipRef}
				role="tooltip"
				style={{
					"--anchor-name": `--${targetId}`,
				} as CSSProperties}
			>
				{renderBody()}
			</div>
		</Fragment>
	);
};

export {
	Tooltip,
};
